### ISSUE TITLE
Add Ascension

### ISSUE THREAD

**Issue by Palmidence** [Minehut/TeamGG-Maps#10]
![](http://i.imgur.com/WH9963J.png)

**Images:** http://imgur.com/a/AHuwY (image descriptions are available in the link)

**Ascension** is a DTW map that consists of three ships, two being team ships and the middle ship acting as a buffer between the two sides. It's a traditional style PvP map for the most part, and was made by ViceWatercolour. Includes .json and map files.

Download: https://www.dropbox.com/s/ohf4d7eucy7mldr/Ascension.zip?dl=0

**NOTE:** Map has also been pruned in MCEdit. It's supposed to play during nighttime, if it doesn't let me know so I can modify it accordingly.

**Comment by tjhubz** [comment]
Added
